AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Include:
    - "app/**/*.rb"
    - "Gemfile"
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "script/**/*"
    - "test/**/*"
    - "vendor/**/*"
    - "init.rb"
    - "lib/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Style/SymbolArray:
  EnforcedStyle: brackets

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Proc:
  Enabled: false
